server:
  port: 8081

spring:
  application:
    name: mcsv-gateway

  cloud:
    gateway:
      routes:
        - id: students
          uri: lb://mcsv-student
          predicates:
            - Path=/api/v1/students/**
          filters:
            - StripPrefix=2
            - AuthFilter
            - name: Resilience4jRateLimiter
              args:
                rateLimiter: studentsRateLimiter
            
        - id: courses
          uri: lb://mcsv-course
          predicates:
            - Path=/api/v1/courses/**
          filters:
            - StripPrefix=2
            - AuthFilter
            - name: Resilience4jRateLimiter
              args:
                rateLimiter: coursesRateLimiter
            
        - id: auth
          uri: lb://microservice-auth
          predicates:
           - Path=/api/v1/auth/**
          filters:
            - StripPrefix=2

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG
    org.springframework.web: DEBUG
    com.netflix.discovery: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://microservice-eureka:8761/eureka
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}


resilience4j.ratelimiter:
  instances:
    studentsRateLimiter:
      limitForPeriod: 3          # máximo 10 peticiones por segundo
      limitRefreshPeriod: 1s
      timeoutDuration: 0
    coursesRateLimiter:
      limitForPeriod: 3           # máximo 5 peticiones por segundo
      limitRefreshPeriod: 1s
      timeoutDuration: 0
