server:
  port: 0

spring:
  application:
    name: mcsv-course
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/course-db
    username: postgres
    password: mysqlronald

  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      cache:
        enabled: true
      health-check:
        initial-delay: 5s
        interval: 5s
        refetch-instances: true

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: false
  sql:
    init:
      mode: always

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true

resilience4j:
  circuitbreaker:
    instances:
      students-service:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 5s
  retry:
    instances:
      students-service-retry:
        max-attempts: 3
        wait-duration: 1s
        retry-exceptions:
          - org.springframework.dao.DataAccessException
          - java.io.IOException
          - feign.RetryableException
  timelimiter:
    instances:
      students-service-timelimiter:
        timeout-duration: 4s

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents,metrics,prometheus

  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true

  metrics:
    tags:
      application: ${spring.application.name}


